config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :categories, only: %i[index new create update edit show]
  get 'category/all-questions/:id', to: 'categories#destroy'
  resources :questions, only: %i[index new create update edit show]
  get 'questions/:id', to: 'questions#destroy'
  root 'pages#index'
  get 'category_select', to: 'quizzes#category_select'
  get 'start', to: 'quizzes#new'
  get 'result', to: 'quizze#result'
  resources :quizzes, only: %i[new create update edit]


  resources :profiles, only: %i[index show]
  get 'users', to: 'profiles#user_list'
  get 'user/results/:id', to: 'profiles#user_quiz'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  has_many :question_categories
  has_many :categories, through: :question_categories
  has_many :answers
  has_many :quiz_questions
  has_many :quizzes, through: :quiz_questions
  accepts_nested_attributes_for :answers, allow_destroy: true, reject_if: :all_blank

  validates :question, presence: true, length: { minimum: 10, maximum: 200 }
  validates_uniqueness_of :question
  validate :answer_validation

  def answer_validation
    errors.add(:option, 'Please select only one correct answer') if answers.map(&:correct).count(true) != 1
  end
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_question, only: %i[show edit update destroy]
  before_action :set_question_answers, only: %i[edit]

  def index
    @questions = Question.paginate(page: params[:page], per_page: 5)
  end

  def new
    @question = Question.new
    @answers = @question.answers.build
  end

  def create
    @question = Question.new(question_params)
    authorize @question
    if @question.save 
      flash[:notice] = "question was sucessfully created."
      redirect_to questions_path
    else 
      render 'new'
    end
  end

  def show; end

  def edit; end

  def update
    authorize @question
    if @question.update(question_params)
      flash[:notice] = 'Question was updated successfully'
      redirect_to @question
    else
      render 'edit'
    end
  end

  def destroy
    @question.destroy
    redirect_to questions_url
    flash[:notice] = 'Question sucessfully deleted.'
  rescue StandardError => e
    flash[:alert] = 'This question might have been used in quiz. '
    redirect_to questions_url
  else
  end

  private

  def question_params
    params.require(:question).permit(:question, category_ids: [],
                                                answers_attributes: %i[id answer correct _destroy])
  end

  def set_question
    @question = Question.find(params[:id])
  end

  def set_question_answers
    @answers = Question.find(params[:id]).answers
  end
end

app/helpers/questions_helper.rb
# frozen_string_literal: true

module QuestionsHelper
end

app/views/questions/_answer.html.erb
<% if user_signed_in? && current_user.admin? %>
  <div class="container mt-sm-5 my-1 pb-5">
      <div class="question ml-sm-5 pl-sm-5 pt-2 shadow p-3 mb-3 bg-info rounded">
        <% opt.each do |answer|%>
          <%= hidden_field(:answer, :id) %>
          <div class= "alert alert-success">
          <div class="custom-control custom-checkbox">
            <%= check_box(:answer, answer.answer, {disabled: true, checked: answer.correct?  ? true : false}) %>
            <%= answer.answer %>
            <br />
          </div>
        </div>
        <% end %>
      </div>
  </div>
<% end %>

app/views/questions/_answer_fields.html.erb
 <div class="form-group row col-8 mb-2">
		<div class="input-group mb-3">
			<div class="input-group-prepend">
				<div class="input-group-text">
					<%= f.check_box :correct, value: true%>
				</div>
			</div>
				<br>
			<%= f.text_field :answer, class: "form-control shadow", placeholder: "Enter the option"%>
			</br>
		</div>
</div>

app/views/questions/_form.html.erb
<div class="container">
<div class="row justify-content-center">
  <div class="col-10">
    <%= render 'shared/errors', obj: @question%>
    <%= form_with(model: question, class: "shadow p-3 mb-3 bg-info rounded") do |form| %>
      <div class="form-group row">
          <%= form.label :question, class:"col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= form.text_field :question, class:"form-control shadow rounded", placeholder: "Enter the question" %>
          </div>
      </div>
      <div class="form-group row">
        <%= form.label :category, class:"col-2 col-form-label text-light" %>
        <div class="col-10">
         <%= form.collection_select(:category_ids, Category.all, :id, :name ,
                                    { prompt:"Make a selection for list below.(can be empty)"}, {multiple: true, size: 3, class: "custom-select shadow rounded", required: true} ) %>
        </div>
      </div>
      <h1> Add answers </h1>
      <div class="form-group row d-flex justify-content-center">
        <%= form.fields_for :answers, id: "form" do |answer| %>
          <%= render 'answer_fields', f: answer%>
        <% end %>
        <%= link_to_add_association "Add Answer", form, :answers %>
      </div>

      <div class="form-group row justify-content-center">
        <%= form.submit class:"btn-btn-outline-light btn-lg" %>
      </div>
      <% end %>
    </div>
    <div class="mb-3">
      <%= link_to '[Cancel and return to questions listing]', questions_path, class: "text-info" %>
    </div>
  </div>
</div>

<script>

(function($) {

  var cocoon_element_counter = 0;

  var create_new_id = function() {
    return (new Date().getTime() + cocoon_element_counter++);
  }

  var newcontent_braced = function(id) {
    return '[' + id + ']$1';
  }

  var newcontent_underscord = function(id) {
    return '_' + id + '_$1';
  }

  var getInsertionNodeElem = function(insertionNode, insertionTraversal, $this){

    if (!insertionNode){
      return $this.parent();
    }

    if (typeof insertionNode == 'function'){
      if(insertionTraversal){
        console.warn('association-insertion-traversal is ignored, because association-insertion-node is given as a function.')
      }
      return insertionNode($this);
    }

    if(typeof insertionNode == 'string'){
      if (insertionTraversal){
        return $this[insertionTraversal](insertionNode);
      }else{
        return insertionNode == "this" ? $this : $(insertionNode);
      }
    }

  }

  $(document).on('click', '.add_fields', function(e) {
    e.preventDefault();
    e.stopPropagation();
    
    var $this                 = $(this),
        assoc                 = $this.data('association'),
        assocs                = $this.data('associations'),
        content               = $this.data('association-insertion-template'),
        insertionMethod       = $this.data('association-insertion-method') || $this.data('association-insertion-position') || 'before',
        insertionNode         = $this.data('association-insertion-node'),
        insertionTraversal    = $this.data('association-insertion-traversal'),
        count                 = parseInt($this.data('count'), 10),
        regexp_braced         = new RegExp('\\[new_' + assoc + '\\](.*?\\s)', 'g'),
        regexp_underscord     = new RegExp('_new_' + assoc + '_(\\w*)', 'g'),
        new_id                = create_new_id(),
        new_content           = content.replace(regexp_braced, newcontent_braced(new_id)),
        new_contents          = [],
        originalEvent         = e;


    if (new_content == content) {
      regexp_braced     = new RegExp('\\[new_' + assocs + '\\](.*?\\s)', 'g');
      regexp_underscord = new RegExp('_new_' + assocs + '_(\\w*)', 'g');
      new_content       = content.replace(regexp_braced, newcontent_braced(new_id));
    }

    new_content = new_content.replace(regexp_underscord, newcontent_underscord(new_id));
    new_contents = [new_content];

    count = (isNaN(count) ? 1 : Math.max(count, 1));
    count -= 1;

    while (count) {
      new_id      = create_new_id();
      new_content = content.replace(regexp_braced, newcontent_braced(new_id));
      new_content = new_content.replace(regexp_underscord, newcontent_underscord(new_id));
      new_contents.push(new_content);

      count -= 1;
    }

    var insertionNodeElem = getInsertionNodeElem(insertionNode, insertionTraversal, $this)

    if( !insertionNodeElem || (insertionNodeElem.length == 0) ){
      console.warn("Couldn't find the element to insert the template. Make sure your `data-association-insertion-*` on `link_to_add_association` is correct.")
    }

    $.each(new_contents, function(i, node) {
      var contentNode = $(node);

      var before_insert = jQuery.Event('cocoon:before-insert');
      insertionNodeElem.trigger(before_insert, [contentNode, originalEvent]);

      if (!before_insert.isDefaultPrevented()) {
        // allow any of the jquery dom manipulation methods (after, before, append, prepend, etc)
        // to be called on the node.  allows the insertion node to be the parent of the inserted
        // code and doesn't force it to be a sibling like after/before does. default: 'before'
        var addedContent = insertionNodeElem[insertionMethod](contentNode);

        insertionNodeElem.trigger('cocoon:after-insert', [contentNode,
          originalEvent]);
      }
    });
  });

  $(document).on('click', '.remove_fields.dynamic, .remove_fields.existing', function(e) {
    var $this = $(this),
        wrapper_class = $this.data('wrapper-class') || 'nested-fields',
        node_to_delete = $this.closest('.' + wrapper_class),
        trigger_node = node_to_delete.parent(),
        originalEvent = e;

    e.preventDefault();
    e.stopPropagation();

    var before_remove = jQuery.Event('cocoon:before-remove');
    trigger_node.trigger(before_remove, [node_to_delete, originalEvent]);

    if (!before_remove.isDefaultPrevented()) {
      var timeout = trigger_node.data('remove-timeout') || 0;

      setTimeout(function() {
        if ($this.hasClass('dynamic')) {
            node_to_delete.detach();
        } else {
            $this.prev("input[type=hidden]").val("1");
            node_to_delete.hide();
        }
        trigger_node.trigger('cocoon:after-remove', [node_to_delete,
          originalEvent]);
      }, timeout);
    }
  });

  var hideRemoveFields = function() {
    $('.remove_fields.existing.destroyed').each(function(i, obj) {
      var $this = $(this),
          wrapper_class = $this.data('wrapper-class') || 'nested-fields';

      $this.closest('.' + wrapper_class).hide();
    });
  };

  $(function() {
    hideRemoveFields();
    $(document).on('page:load turbolinks:load turbo:load', hideRemoveFields); // Turbolinks support
  });
  
})(jQuery);
</script>

app/views/questions/_question.html.erb
  <% opt.each do |question| %>
    <div class="row justify-content-md-center"> 
      <div class = "col-8 mt-4"> 
        <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
           <% if question.categories.any?%>
            <div class="md-2"><%= question.categories.map(&:name) %> </div>
          <% end %>
        </div>
       
        <div class="card-body">
          <h5 class="card-title"><%=  link_to question.question, question_path(question), class:"text-success" %></h5>
          <%= link_to 'Answers',  question_path(question), class: "btn btn-outline-success" %>
          <%= link_to 'Edit',  edit_question_path(question), class:"btn btn-outline-success" %>
          <%= link_to 'Destroy', "question_delete/#{question.id}", class:"btn btn-outline-danger", data: { confirm: 'Are you sure?' } %>
        </div>

        <div class="card-footer text-muted">
          <small> Created  <%= time_ago_in_words(question.created_at) %>  ago,
            updated <%= time_ago_in_words(question.updated_at) %>  ago
          </small>
        </div>
        </div>
      </div>
      </div>
  <% end %>
</div>

app/views/questions/edit.html.erb
<h1 class="text-center mt-4">Edit Question</h1>
<%= render 'form', question: @question, answers: @answers %>

app/views/questions/index.html.erb
<% if user_signed_in? && current_user.admin?%>
  <h1 class="text-center mt-4">Listing all  Questions</h1>
  <div class="container shadow p-3 mb-3 bg-info rounded"> 
    <div class="text-center mt-4 mb-3">
      <%= link_to 'New Question', new_question_path, class:"btn btn-outline-primary" %>
    </div>
    <%= render 'shared/pagination', opt: @questions%>
    <%= render 'question', opt: @questions %>
    <%= render 'shared/pagination', opt: @questions, loc: ["mb-4"]%>
  </div>
  <% end %>

app/views/questions/new.html.erb
<h1 class="text-center mt-4">Create a new question</h1>
<%= render 'form', question: @question %>

app/views/questions/show.html.erb
<% if user_signed_in? && current_user.admin? %>
  <h1 class="text-center mt-4"> Question: <%= @question.question%></h1>

    <div class="text-center mt-4">
      <%= link_to "Edit Question", edit_question_path(@question), class: "btn btn-outline-info" %>
    </div>
  <h3 class="text-center mt-4">Answer</h3>
  <%= render 'answer', opt: @question.answers %>
<% end %>