config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :categories, only: %i[index new create update edit show]
  get 'category/all-questions/:id', to: 'categories#destroy'
  resources :questions, only: %i[index new create update edit show]
  get 'questions/:id', to: 'questions#destroy'
  root 'pages#index'
  get 'category_select', to: 'quizzes#category_select'
  get 'start', to: 'quizzes#new'
  get 'result', to: 'quizze#result'
  resources :quizzes, only: %i[new create update edit]


  resources :profiles, only: %i[index show]
  get 'users', to: 'profiles#user_list'
  get 'user/results/:id', to: 'profiles#user_quiz'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/profiles_controller.rb
# frozen_string_literal: true

class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_quiz, only: [:show]

  def index
    @quizzes = Quiz.all.where(user_id: current_user.id).paginate(page: params[:page], per_page: 5)
  end

  def user_list
    @users = User.where(admin: false).paginate(page: params[:page], per_page: 5)
  end

  def user_quiz
    @quizzes = User.find(params[:id]).quizzes.paginate(page: params[:page], per_page: 5)
  end

  def show
    if @quiz.present?
      @results = @quiz.quiz_questions
      @quiz
    else
      flash[:notice] = "You havn't perfom a quiz yet!"
      render 'index'
    end
  end

  private

  def set_quiz
    @quiz = Quiz.find(params[:id])
  end
end

app/helpers/profiles_helper.rb
# frozen_string_literal: true

module ProfilesHelper
end

app/views/profiles/_quizzes.html.erb
<% quizzes.each do |quiz| %>
      <div class="row justify-content-md-center"> 
        <div class = "col-4 mt-4"> 
          <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-body">
            <h5 class="card-title"><%=  link_to quiz.name, profile_path(quiz), class:"text-success" %></h5>
            <p class="card-text">Total Questions:  <%= quiz.total_question %></p>
            <p class="card-text">Total Correct Answer: <%= quiz.total_correct_answer %></p>
            <p class="card-text">Percentage: <%= quiz.percentage %>%</p>
          </div>

          <div class="card-footer text-muted">
              held on <%= time_ago_in_words(quiz.updated_at) %>  ago
            </small>
          </div>
          </div>
        </div>
        </div>
    <% end %>

app/views/profiles/index.html.erb
<% if @quizzes.present?%>
<h1 class="text-center mt-4">Listing all  quizzes of <%= current_user.name%></h1>
  <div class="container shadow p-3 mb-3 bg-info rounded"> 
    <%= render 'shared/pagination', opt: @quizzes%>
    <% @quizzes.each do |quiz| %>
      <div class="row justify-content-md-center"> 
        <div class = "col-4 mt-4"> 
          <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-body">
            <h5 class="card-title"><%=  link_to quiz.name, profile_path(quiz), class:"text-success" %></h5>
            <p class="card-text">Total Questions:  <%= quiz.total_question %></p>
            <p class="card-text">Total Correct Answer: <%= quiz.total_correct_answer %></p>
            <p class="card-text">Percentage: <%= quiz.percentage %>%</p>
          </div>

          <div class="card-footer text-muted">
              held on <%= time_ago_in_words(quiz.updated_at) %>  ago
            </small>
          </div>
          </div>
        </div>
        </div>
    <% end %>
    <%= render 'shared/pagination', opt: @quizzes, loc: ["mb-4"]%>
  </div>
<% else  %>
  <div class= "row justify-content-center mt-3 mb-3 pb-5">
    <%= link_to "Start Quiz", category_select_path, class: "btn btn-outline-info" %>
  </div>
<% end %>
 

app/views/profiles/show.html.erb
<div class="container">
  <div class="row justify-content-center">
  <h1> Quiz result of  <%= current_user.name %> </h1>
    <%= render 'quizzes/report', opt: @results%>
  </div>
</div>
  

app/views/profiles/user_list.html.erb
<h1 class="text-center mt-4">Listing all  Users</h1>
<div class="container shadow p-3 mb-3 bg-info rounded"> 
  <%= render 'shared/pagination', opt: @users%>
  <% @users.each do |user| %>
    <div class="row justify-content-md-center"> 
      <div class = "col-4 mt-4"> 
        <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-body">
          <h5 class="card-title"><%=  link_to user.name, "user/results/#{user.id}", class:"text-success" %></h5>
           <p class="card-text"> <%= pluralize(user.quizzes.count, "quiz") %></p>
        </div>
        <div class="card-footer text-muted">
          <small> Created  <%= time_ago_in_words(user.created_at) %>  ago,
            updated <%= time_ago_in_words(user.updated_at) %>  ago
          </small>
        </div>
        </div>
      </div>
      </div>
  <% end %>
  <%= render 'shared/pagination', opt: @users, loc: ["mb-4"]%>
</div>

app/views/profiles/user_quiz.html.erb
<% if @quizzes.present?%>
<h1 class="text-center mt-4">Listing all  quizzes of <%= @quizzes.first.user.name%></h1>
  <div class="container shadow p-3 mb-3 bg-info rounded"> 
    <%= render 'shared/pagination', opt: @quizzes%>
    <%= render 'quizzes', quizzes: @quizzes%>
  
    <%= render 'shared/pagination', opt: @quizzes, loc: ["mb-4"]%>
  </div>
<% else  %>
  <div class= "row justify-content-center mt-3 mb-3 pb-5">
    <%= link_to "Start Quiz", category_select_path, class: "btn btn-outline-info" %>
  </div>
<% end %>
 