config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :categories, only: %i[index new create update edit show]
  get 'category/all-questions/:id', to: 'categories#destroy'
  resources :questions, only: %i[index new create update edit show]
  get 'questions/:id', to: 'questions#destroy'
  root 'pages#index'
  get 'category_select', to: 'quizzes#category_select'
  get 'start', to: 'quizzes#new'
  get 'result', to: 'quizze#result'
  resources :quizzes, only: %i[new create update edit]


  resources :profiles, only: %i[index show]
  get 'users', to: 'profiles#user_list'
  get 'user/results/:id', to: 'profiles#user_quiz'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :question_categories
  has_many :questions, through: :question_categories

  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[show edit update destroy]

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def show; end

  def new
    @category = Category.new
  end

  def edit; end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = 'Category sucessfully created.'
      redirect_to @category
    else
      render 'new'
    end
  end

  def update
    if @category.update(category_params)
      flash[:notice] = 'Category name was updated successfully'
      redirect_to @category
    else
      render 'edit'
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_url
    flash[:notice] = 'Category sucessfully deleted.'
  rescue StandardError => e
    flash[:alert] = 'This Categories questions might have been used in quiz. '
    redirect_to categories_url
  else
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

app/views/categories/_form.html.erb
<div class="container">
<div class="row justify-content-center">
  <div class="col-10">
    <%= render 'shared/errors', obj: @category%>
    <%= form_with(model: category, class: "shadow p-3 mb-3 bg-info rounded") do |form| %>
      <div class="form-group row">
          <%= form.label :name, "Category Name", class:"col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= form.text_field :name, class:"form-control shadow rounded", placeholder: "Enter a name" %>
          </div>
      </div>

      <div class="form-group row justify-content-center">
        <%= form.submit class:"btn-btn-outline-light btn-lg" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/categories/edit.html.erb
<h1 class="text-center mt-4">Edit category</h1>
<%= render 'form', category: @category %>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">Listing all  categories</h1>
<div class="container shadow p-3 mb-3 bg-info rounded"> 
   <div class="text-center mt-4 mb-3">
    <%= link_to 'New Category', new_category_path, class:"btn btn-outline-primary" %>
  </div>
  <%= render 'shared/pagination', opt: @categories%>
  <% @categories.each do |category| %>
    <div class="row justify-content-md-center"> 
      <div class = "col-4 mt-4"> 
        <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-body">
          <h5 class="card-title"><%=  link_to category.name, category_path(category), class:"text-success" %></h5>
           <p class="card-text"> <%= pluralize(category.questions.count, "question") %></p>
          <%= link_to 'Edit',  edit_category_path(category), class:"btn btn-outline-success" %>
          <%= link_to 'Destroy', "category/all-questions/#{category.id}", class:"btn btn-outline-danger", data: { confirm: 'Are you sure?' } %>
        </div>
        <div class="card-footer text-muted">
          <small> Created  <%= time_ago_in_words(category.created_at) %>  ago,
            updated <%= time_ago_in_words(category.updated_at) %>  ago
          </small>
        </div>
        </div>
      </div>
      </div>
  <% end %>
  <%= render 'shared/pagination', opt: @categories, loc: ["mb-4"]%>
</div>

app/views/categories/new.html.erb
<h1 class="text-center mt-4">Create a new category</h1>
<%= render 'form', category: @category %>

app/views/categories/show.html.erb
<h1 class="text-center mt-4"> Category: <%= @category.name%></h1>
<% if user_signed_in? && current_user.admin? %>
  <div class="text-center mt-4">
    <%= link_to "Edit category name", edit_category_path(@category), class: "btn btn-outline-info" %>
    <%= link_to 'New Category', new_category_path, class:"btn btn-outline-primary" %>
  </div>
<% end %>
<h3 class="text-center mt-4">Questions</h3>
 <%= render 'questions/question', opt: @category.questions%>