config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :categories, only: %i[index new create update edit show]
  get 'category/all-questions/:id', to: 'categories#destroy'
  resources :questions, only: %i[index new create update edit show]
  get 'questions/:id', to: 'questions#destroy'
  root 'pages#index'
  get 'category_select', to: 'quizzes#category_select'
  get 'start', to: 'quizzes#new'
  get 'result', to: 'quizze#result'
  resources :quizzes, only: %i[new create update edit]


  resources :profiles, only: %i[index show]
  get 'users', to: 'profiles#user_list'
  get 'user/results/:id', to: 'profiles#user_quiz'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  belongs_to :question

  validates :answer, presence: true, length: { minimum: 3, maximum: 200 }
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :question_categories
  has_many :questions, through: :question_categories

  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  has_many :question_categories
  has_many :categories, through: :question_categories
  has_many :answers
  has_many :quiz_questions
  has_many :quizzes, through: :quiz_questions
  accepts_nested_attributes_for :answers, allow_destroy: true, reject_if: :all_blank

  validates :question, presence: true, length: { minimum: 10, maximum: 200 }
  validates_uniqueness_of :question
  validate :answer_validation

  def answer_validation
    errors.add(:option, 'Please select only one correct answer') if answers.map(&:correct).count(true) != 1
  end
end

app/models/question_category.rb
# frozen_string_literal: true

class QuestionCategory < ApplicationRecord
  belongs_to :category
  belongs_to :question
end

app/models/quiz.rb
# frozen_string_literal: true

class Quiz < ApplicationRecord
  has_many :quiz_questions
  has_many :questions, through: :quiz_questions
  belongs_to :user, optional: true

  validates  :name,  presence: true
  validates_uniqueness_of :name
end

app/models/quiz_question.rb
# frozen_string_literal: true

class QuizQuestion < ApplicationRecord
  belongs_to :quiz
  belongs_to :question
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :quizzes
end

app/controllers/answers_controller.rb
# frozen_string_literal: true

class AnswersController < ApplicationController
  before_action :authenticate_user!

  def new
    @answer = Answer.new
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def index; end
end

app/controllers/profiles_controller.rb
# frozen_string_literal: true

class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_quiz, only: [:show]

  def index
    @quizzes = Quiz.all.where(user_id: current_user.id).paginate(page: params[:page], per_page: 5)
  end

  def user_list
    @users = User.where(admin: false).paginate(page: params[:page], per_page: 5)
  end

  def user_quiz
    @quizzes = User.find(params[:id]).quizzes.paginate(page: params[:page], per_page: 5)
  end

  def show
    if @quiz.present?
      @results = @quiz.quiz_questions
      @quiz
    else
      flash[:notice] = "You havn't perfom a quiz yet!"
      render 'index'
    end
  end

  private

  def set_quiz
    @quiz = Quiz.find(params[:id])
  end
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_question, only: %i[show edit update destroy]
  before_action :set_question_answers, only: %i[edit]

  def index
    @questions = Question.paginate(page: params[:page], per_page: 5)
  end

  def new
    @question = Question.new
    @answers = @question.answers.build
  end

  def create
    @question = Question.new(question_params)
    authorize @question
    if @question.save 
      flash[:notice] = "question was sucessfully created."
      redirect_to questions_path
    else 
      render 'new'
    end
  end

  def show; end

  def edit; end

  def update
    authorize @question
    if @question.update(question_params)
      flash[:notice] = 'Question was updated successfully'
      redirect_to @question
    else
      render 'edit'
    end
  end

  def destroy
    @question.destroy
    redirect_to questions_url
    flash[:notice] = 'Question sucessfully deleted.'
  rescue StandardError => e
    flash[:alert] = 'This question might have been used in quiz. '
    redirect_to questions_url
  else
  end

  private

  def question_params
    params.require(:question).permit(:question, category_ids: [],
                                                answers_attributes: %i[id answer correct _destroy])
  end

  def set_question
    @question = Question.find(params[:id])
  end

  def set_question_answers
    @answers = Question.find(params[:id]).answers
  end
end

app/controllers/quizzes_controller.rb
# frozen_string_literal: true

class QuizzesController < ApplicationController
  before_action :set_quiz, only: [:create]
  before_action :authenticate_user!, only: [:result]

  def category_select
    render 'category_select'
  end

  def new
    if !params[:category_ids].empty?
      @guest_email = params[:email] if params[:email]
      @questions = []
      @questions.push(categories_question)
      create_quiz if @questions.flatten!
      @questions
      @quiz
    else
      flash[:error] = 'please select the category!'
      redirect_to category_select_path
    end
  end

  def create
    QuizQuestion.where(quiz_id: params[:quiz_id]).each do |quiz_question|
      puts "id is #{params["#{quiz_question.question_id}"]}"
       quiz_question.update(given_answer: params["#{quiz_question.question_id}"])
       if quiz_question.given_answer != nil
        correct_answer(quiz_question.given_answer)
       end
    end
    if overall
      quiz = @quiz
      send_email(set_email, result, quiz)
      result
      @quiz
      flash[:notice] = 'You have sucessfully attempted the quiz.'
      render 'result'
    end
  end

  def result
    @results = @quiz.quiz_questions
  end

  def send_email(email, result, quiz)
    quiz = @quiz
    ReportMailer.quiz_report(email, result, quiz).deliver
  end

  private

  def set_quiz
    @quiz = Quiz.find(params[:quiz_id])
  end

  def set_email
    if user_signed_in?
      current_user.email
    else
      params[:email]
    end
  end

  def correct_answer(id)
    if Answer.find(id).correct? 
      @total_correct_answer = @total_correct_answer.nil? ? 1 : @total_correct_answer + 1
    end
  end

  def overall
    @quiz.update(total_correct_answer: @total_correct_answer.nil? ? 0 : @total_correct_answer,
                 percentage: calculate_percentage.round(2))
  end

  def calculate_percentage
    @total_correct_answer.nil? ? @quiz.total_correct_answer : @total_correct_answer / @quiz.total_question.to_f * 100
  end

  def all_questions
    Question.all
  end

  def categories_question
    Category.find(params[:category_ids])&.questions
  end

  def create_quiz
    @quiz = Quiz.new
    @quiz.name =   "#{@questions.first.categories.first.name}-#{Time.now} "
    @quiz.total_question = @questions.count
    @quiz.user_id = current_user.id if current_user
    quiz_question(@quiz.id) if @quiz.save
  end

  def quiz_question(quiz_id)
    @questions.each do |question|
      QuizQuestion.create(quiz_id: quiz_id, question_id: question.id)
    end
  end
end

app/helpers/answers_helper.rb
# frozen_string_literal: true

module AnswersHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/helpers/profiles_helper.rb
# frozen_string_literal: true

module ProfilesHelper
end

app/helpers/questions_helper.rb
# frozen_string_literal: true

module QuestionsHelper
end

app/helpers/quizzes_helper.rb
# frozen_string_literal: true

module QuizzesHelper
end

app/views/layouts/_footer.html.erb
<footer class="fixed-bottom py-4 bg-dark text-white">
    <div class="container text-center">
      <small>Copyright &copy; Binod Paneru</small>
    </div>
 </footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Quize", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
       <% if user_signed_in? %>
          <% if current_user.admin? %>
            <li class="nav-item">
                <%= link_to "Categories", categories_path,  class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Questions", questions_path,  class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Results", users_path,  class: "nav-link" %>
            </li>
          <% end %>
        <li class="nav-item">
          <%= link_to  current_user.admin? ? "(Admin)#{current_user.name}" : current_user.name , profiles_path,  class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Logout", destroy_user_session_path, method: :delete,  class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Sing up", new_user_registration_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Guest User Quiz", category_select_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quize</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
  </head>

  <body>
  <div>
   <%= render 'layouts/navigation' %>
    <div id="page-content">
    <%= render 'layouts/messages'%>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<div  class="container pad-100" id="home-container">
  <div class="jumbotron text-center text-black shadow p-3 mb-3 bg-alert rounded">
    <h1 class="display-4 pad-top-80">Welcome to the quiz</h1>
    <p class="lead">Lets get started</p>
    <hr class="my-4">
      <% if !user_signed_in? %>
        <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-outline-info btn-lg" %> 
        <p class="lead mb-3 mt-3">Or</p>
        <hr class="my-4">
      <% end %>
       <%= link_to "Start Quiz", category_select_path, class: "btn btn-outline-info btn-lg" %> 
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The follwoing errors prevented the <%= obj.class.name.downcase  %>  from beign saved. </h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg%></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_pagination.html.erb
<div class="flickr_pagination <%= (defined?loc).nil?  ? '' : loc.first %>">
    <%= will_paginate opt, :container => false %>
</div>